{{- if .Values.development }}
apiVersion: v1
data:
  lodestar-runtime-config.yaml: |
   ---
   basic_information:
     project_name:
       validators:
         - kind: regex
           value: ^\w+[\w- ()]*$
           message: Only alphanumeric characters and spaces are allowed
     customer_name:
       validators:
         - kind: regex
           value: ^\w+[\w- ()]*$
           message: Only alphanumeric characters and spaces are allowed
   cloud_options:
     providers:
       options:
         - label: AWS
           value: ec2
           options:
             - label: US East 1 (N. Virginia)
               value: us-east-1
             - label: US East 2 (Ohio)
               value: us-east-2
             - label: US West 1 (N. California)
               value: us-west-1
             - label: US West 2 (Oregon)
               value: us-west-2
         - label: Other
           value: other
           options:
             - label: Other
               value: other
   openshift_options:
     versions:
       options:
         - label: v4.4
           value: 4.4.10
         - label: v4.5
           value: 4.5.0
     persistent_storage:
       validators:
         - kind: notnull
       options:
         - label: None
           value: none
         - label: 50GB
           value: 50G
     cluster_size:
       options:
         - label: Small
           value: small
   user_options:
     user_roles:
       options:
         - label: Developer
           value: developer
         - label: Observer
           value: observer
         - label: Admin
           value: admin
   logistics_options:
     start_date:
     end_date:
       validators:
         - kind: date
           value:
             min: "@today"
           message: "End date must be after today"
     technical_contact_email:
     env_default_grace_period: 30
     env_grace_period_max: 180
kind: ConfigMap
metadata:
  name: lodestar-runtime-cm
{{- end }}
