{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: omp-gitlab-configuration
type: Opaque
stringData:
  CONFIG_FILE: "{{ .Values.configFile }}"
  CONFIG_REPOSITORY_ID: "{{ .Values.configRepositoryId }}"
  DEPLOY_KEY: "{{ .Values.deployKey }}"
  GITLAB_API_URL: "{{ .Values.gitLabApiUrl }}"
  GITLAB_PERSONAL_ACCESS_TOKEN: "{{ .Values.gitLabPersonalAccessToken }}"
  ENGAGEMENTS_REPOSITORY_ID: "{{ .Values.engagementsRepositoryId }}"
  WEBHOOK_FILE: "{{ .Values.config.hookFile.path }}/{{ .Values.config.hookFile.name }}"
  CONFIG_GITLAB_REF: "{{ .Values.gitlabRef }}"
{{- end }}
