build_vars:
  NAME: omp-git-api
  GIT_URL: https://github.com/rht-labs/open-management-portal-git-api.git
  GIT_REF: master
  OUTPUT_IMAGE_NAME: omp-git-api
  OUTPUT_IMAGE_TAG: latest
  BUILDER_IMAGE_NAME: quay.io/quarkus/ubi-quarkus-native-s2i
  BUILDER_IMAGE_TAG: 19.2.1

deploy_vars:
  NAME: omp-git-api
  IMAGE_NAME: omp-git-api
  IMAGE_TAG: latest

openshift_cluster_content:
- object: omp-git-api
  content:
  - name: build
    template: '{{ inventory_dir }}/../templates/build.yml'
    params_from_vars: '{{ build_vars }}'
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ deploy_vars }}'
