name: omp-git-api
development: true

servicePort: 8080

imageName: "omp-git-api"
imageTag: "latest"

builderImage: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
builderImageTag: 1.8

git:
  uri: https://github.com/rht-labs/open-management-portal-git-api.git
  ref: master

configFile: false
configRepositoryId: false
deployKey: false
gitLabApiUrl: false
gitLabPersonalAccessToken: false
engagementsRepositoryId: false

config:
  hookFile:
    path: /schema
    name: webhooks.yaml
  hooks:
    - name: hook1
      baseUrl: http://localhost/hook1
      token: ibaka
    - name: hook2
      baseUrl: http://localhost/hook2
      token: anunoby
      